// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

/**
 * Protobuf type {@code com.pacman.protobuf.Map}
 */
public final class Map extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.pacman.protobuf.Map)
    MapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Map.newBuilder() to construct.
  private Map(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Map() {
    cells_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Map();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Map(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sizeX_ = input.readInt32();
            break;
          }
          case 16: {

            sizeY_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              cells_ = new java.util.ArrayList<com.pacman.protobuf.Map.Cell>();
              mutable_bitField0_ |= 0x00000001;
            }
            cells_.add(
                input.readMessage(com.pacman.protobuf.Map.Cell.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        cells_ = java.util.Collections.unmodifiableList(cells_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pacman.protobuf.Map.class, com.pacman.protobuf.Map.Builder.class);
  }

  /**
   * Protobuf enum {@code com.pacman.protobuf.Map.CellState}
   */
  public enum CellState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WALL = 0;</code>
     */
    WALL(0),
    /**
     * <code>EMPTY = 1;</code>
     */
    EMPTY(1),
    /**
     * <code>POINT = 2;</code>
     */
    POINT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WALL = 0;</code>
     */
    public static final int WALL_VALUE = 0;
    /**
     * <code>EMPTY = 1;</code>
     */
    public static final int EMPTY_VALUE = 1;
    /**
     * <code>POINT = 2;</code>
     */
    public static final int POINT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CellState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CellState forNumber(int value) {
      switch (value) {
        case 0: return WALL;
        case 1: return EMPTY;
        case 2: return POINT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CellState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CellState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CellState>() {
            public CellState findValueByNumber(int number) {
              return CellState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.pacman.protobuf.Map.getDescriptor().getEnumTypes().get(0);
    }

    private static final CellState[] VALUES = values();

    public static CellState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CellState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.pacman.protobuf.Map.CellState)
  }

  public interface CellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.Map.Cell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
     * @return The state.
     */
    com.pacman.protobuf.Map.CellState getState();
  }
  /**
   * Protobuf type {@code com.pacman.protobuf.Map.Cell}
   */
  public static final class Cell extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pacman.protobuf.Map.Cell)
      CellOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cell.newBuilder() to construct.
    private Cell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cell() {
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cell();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_Cell_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_Cell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pacman.protobuf.Map.Cell.class, com.pacman.protobuf.Map.Cell.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
     * @return The state.
     */
    @java.lang.Override public com.pacman.protobuf.Map.CellState getState() {
      @SuppressWarnings("deprecation")
      com.pacman.protobuf.Map.CellState result = com.pacman.protobuf.Map.CellState.valueOf(state_);
      return result == null ? com.pacman.protobuf.Map.CellState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (state_ != com.pacman.protobuf.Map.CellState.WALL.getNumber()) {
        output.writeEnum(3, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (state_ != com.pacman.protobuf.Map.CellState.WALL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pacman.protobuf.Map.Cell)) {
        return super.equals(obj);
      }
      com.pacman.protobuf.Map.Cell other = (com.pacman.protobuf.Map.Cell) obj;

      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (state_ != other.state_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pacman.protobuf.Map.Cell parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pacman.protobuf.Map.Cell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pacman.protobuf.Map.Cell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pacman.protobuf.Map.Cell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pacman.protobuf.Map.Cell prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pacman.protobuf.Map.Cell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pacman.protobuf.Map.Cell)
        com.pacman.protobuf.Map.CellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_Cell_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_Cell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pacman.protobuf.Map.Cell.class, com.pacman.protobuf.Map.Cell.Builder.class);
      }

      // Construct using com.pacman.protobuf.Map.Cell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_Cell_descriptor;
      }

      @java.lang.Override
      public com.pacman.protobuf.Map.Cell getDefaultInstanceForType() {
        return com.pacman.protobuf.Map.Cell.getDefaultInstance();
      }

      @java.lang.Override
      public com.pacman.protobuf.Map.Cell build() {
        com.pacman.protobuf.Map.Cell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pacman.protobuf.Map.Cell buildPartial() {
        com.pacman.protobuf.Map.Cell result = new com.pacman.protobuf.Map.Cell(this);
        result.x_ = x_;
        result.y_ = y_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pacman.protobuf.Map.Cell) {
          return mergeFrom((com.pacman.protobuf.Map.Cell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pacman.protobuf.Map.Cell other) {
        if (other == com.pacman.protobuf.Map.Cell.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pacman.protobuf.Map.Cell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pacman.protobuf.Map.Cell) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.pacman.protobuf.Map.CellState getState() {
        @SuppressWarnings("deprecation")
        com.pacman.protobuf.Map.CellState result = com.pacman.protobuf.Map.CellState.valueOf(state_);
        return result == null ? com.pacman.protobuf.Map.CellState.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.pacman.protobuf.Map.CellState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.pacman.protobuf.Map.CellState state = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.pacman.protobuf.Map.Cell)
    }

    // @@protoc_insertion_point(class_scope:com.pacman.protobuf.Map.Cell)
    private static final com.pacman.protobuf.Map.Cell DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pacman.protobuf.Map.Cell();
    }

    public static com.pacman.protobuf.Map.Cell getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cell>
        PARSER = new com.google.protobuf.AbstractParser<Cell>() {
      @java.lang.Override
      public Cell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cell(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cell> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cell> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pacman.protobuf.Map.Cell getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SIZEX_FIELD_NUMBER = 1;
  private int sizeX_;
  /**
   * <code>int32 sizeX = 1;</code>
   * @return The sizeX.
   */
  @java.lang.Override
  public int getSizeX() {
    return sizeX_;
  }

  public static final int SIZEY_FIELD_NUMBER = 2;
  private int sizeY_;
  /**
   * <code>int32 sizeY = 2;</code>
   * @return The sizeY.
   */
  @java.lang.Override
  public int getSizeY() {
    return sizeY_;
  }

  public static final int CELLS_FIELD_NUMBER = 4;
  private java.util.List<com.pacman.protobuf.Map.Cell> cells_;
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.pacman.protobuf.Map.Cell> getCellsList() {
    return cells_;
  }
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.pacman.protobuf.Map.CellOrBuilder> 
      getCellsOrBuilderList() {
    return cells_;
  }
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  @java.lang.Override
  public int getCellsCount() {
    return cells_.size();
  }
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  @java.lang.Override
  public com.pacman.protobuf.Map.Cell getCells(int index) {
    return cells_.get(index);
  }
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  @java.lang.Override
  public com.pacman.protobuf.Map.CellOrBuilder getCellsOrBuilder(
      int index) {
    return cells_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sizeX_ != 0) {
      output.writeInt32(1, sizeX_);
    }
    if (sizeY_ != 0) {
      output.writeInt32(2, sizeY_);
    }
    for (int i = 0; i < cells_.size(); i++) {
      output.writeMessage(4, cells_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sizeX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sizeX_);
    }
    if (sizeY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, sizeY_);
    }
    for (int i = 0; i < cells_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, cells_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pacman.protobuf.Map)) {
      return super.equals(obj);
    }
    com.pacman.protobuf.Map other = (com.pacman.protobuf.Map) obj;

    if (getSizeX()
        != other.getSizeX()) return false;
    if (getSizeY()
        != other.getSizeY()) return false;
    if (!getCellsList()
        .equals(other.getCellsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIZEX_FIELD_NUMBER;
    hash = (53 * hash) + getSizeX();
    hash = (37 * hash) + SIZEY_FIELD_NUMBER;
    hash = (53 * hash) + getSizeY();
    if (getCellsCount() > 0) {
      hash = (37 * hash) + CELLS_FIELD_NUMBER;
      hash = (53 * hash) + getCellsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pacman.protobuf.Map parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Map parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Map parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Map parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Map parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Map parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Map parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Map parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.Map parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Map parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.Map parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Map parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pacman.protobuf.Map prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.pacman.protobuf.Map}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.pacman.protobuf.Map)
      com.pacman.protobuf.MapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pacman.protobuf.Map.class, com.pacman.protobuf.Map.Builder.class);
    }

    // Construct using com.pacman.protobuf.Map.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCellsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sizeX_ = 0;

      sizeY_ = 0;

      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cellsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Map_descriptor;
    }

    @java.lang.Override
    public com.pacman.protobuf.Map getDefaultInstanceForType() {
      return com.pacman.protobuf.Map.getDefaultInstance();
    }

    @java.lang.Override
    public com.pacman.protobuf.Map build() {
      com.pacman.protobuf.Map result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pacman.protobuf.Map buildPartial() {
      com.pacman.protobuf.Map result = new com.pacman.protobuf.Map(this);
      int from_bitField0_ = bitField0_;
      result.sizeX_ = sizeX_;
      result.sizeY_ = sizeY_;
      if (cellsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cells_ = cells_;
      } else {
        result.cells_ = cellsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pacman.protobuf.Map) {
        return mergeFrom((com.pacman.protobuf.Map)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pacman.protobuf.Map other) {
      if (other == com.pacman.protobuf.Map.getDefaultInstance()) return this;
      if (other.getSizeX() != 0) {
        setSizeX(other.getSizeX());
      }
      if (other.getSizeY() != 0) {
        setSizeY(other.getSizeY());
      }
      if (cellsBuilder_ == null) {
        if (!other.cells_.isEmpty()) {
          if (cells_.isEmpty()) {
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCellsIsMutable();
            cells_.addAll(other.cells_);
          }
          onChanged();
        }
      } else {
        if (!other.cells_.isEmpty()) {
          if (cellsBuilder_.isEmpty()) {
            cellsBuilder_.dispose();
            cellsBuilder_ = null;
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cellsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCellsFieldBuilder() : null;
          } else {
            cellsBuilder_.addAllMessages(other.cells_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pacman.protobuf.Map parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pacman.protobuf.Map) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int sizeX_ ;
    /**
     * <code>int32 sizeX = 1;</code>
     * @return The sizeX.
     */
    @java.lang.Override
    public int getSizeX() {
      return sizeX_;
    }
    /**
     * <code>int32 sizeX = 1;</code>
     * @param value The sizeX to set.
     * @return This builder for chaining.
     */
    public Builder setSizeX(int value) {
      
      sizeX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sizeX = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSizeX() {
      
      sizeX_ = 0;
      onChanged();
      return this;
    }

    private int sizeY_ ;
    /**
     * <code>int32 sizeY = 2;</code>
     * @return The sizeY.
     */
    @java.lang.Override
    public int getSizeY() {
      return sizeY_;
    }
    /**
     * <code>int32 sizeY = 2;</code>
     * @param value The sizeY to set.
     * @return This builder for chaining.
     */
    public Builder setSizeY(int value) {
      
      sizeY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sizeY = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSizeY() {
      
      sizeY_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.pacman.protobuf.Map.Cell> cells_ =
      java.util.Collections.emptyList();
    private void ensureCellsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cells_ = new java.util.ArrayList<com.pacman.protobuf.Map.Cell>(cells_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pacman.protobuf.Map.Cell, com.pacman.protobuf.Map.Cell.Builder, com.pacman.protobuf.Map.CellOrBuilder> cellsBuilder_;

    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public java.util.List<com.pacman.protobuf.Map.Cell> getCellsList() {
      if (cellsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cells_);
      } else {
        return cellsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public int getCellsCount() {
      if (cellsBuilder_ == null) {
        return cells_.size();
      } else {
        return cellsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public com.pacman.protobuf.Map.Cell getCells(int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);
      } else {
        return cellsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder setCells(
        int index, com.pacman.protobuf.Map.Cell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.set(index, value);
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder setCells(
        int index, com.pacman.protobuf.Map.Cell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.set(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder addCells(com.pacman.protobuf.Map.Cell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder addCells(
        int index, com.pacman.protobuf.Map.Cell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(index, value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder addCells(
        com.pacman.protobuf.Map.Cell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder addCells(
        int index, com.pacman.protobuf.Map.Cell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder addAllCells(
        java.lang.Iterable<? extends com.pacman.protobuf.Map.Cell> values) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cells_);
        onChanged();
      } else {
        cellsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder clearCells() {
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cellsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public Builder removeCells(int index) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.remove(index);
        onChanged();
      } else {
        cellsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public com.pacman.protobuf.Map.Cell.Builder getCellsBuilder(
        int index) {
      return getCellsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public com.pacman.protobuf.Map.CellOrBuilder getCellsOrBuilder(
        int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);  } else {
        return cellsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public java.util.List<? extends com.pacman.protobuf.Map.CellOrBuilder> 
         getCellsOrBuilderList() {
      if (cellsBuilder_ != null) {
        return cellsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cells_);
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public com.pacman.protobuf.Map.Cell.Builder addCellsBuilder() {
      return getCellsFieldBuilder().addBuilder(
          com.pacman.protobuf.Map.Cell.getDefaultInstance());
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public com.pacman.protobuf.Map.Cell.Builder addCellsBuilder(
        int index) {
      return getCellsFieldBuilder().addBuilder(
          index, com.pacman.protobuf.Map.Cell.getDefaultInstance());
    }
    /**
     * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
     */
    public java.util.List<com.pacman.protobuf.Map.Cell.Builder> 
         getCellsBuilderList() {
      return getCellsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pacman.protobuf.Map.Cell, com.pacman.protobuf.Map.Cell.Builder, com.pacman.protobuf.Map.CellOrBuilder> 
        getCellsFieldBuilder() {
      if (cellsBuilder_ == null) {
        cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.pacman.protobuf.Map.Cell, com.pacman.protobuf.Map.Cell.Builder, com.pacman.protobuf.Map.CellOrBuilder>(
                cells_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cells_ = null;
      }
      return cellsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.pacman.protobuf.Map)
  }

  // @@protoc_insertion_point(class_scope:com.pacman.protobuf.Map)
  private static final com.pacman.protobuf.Map DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pacman.protobuf.Map();
  }

  public static com.pacman.protobuf.Map getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Map>
      PARSER = new com.google.protobuf.AbstractParser<Map>() {
    @java.lang.Override
    public Map parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Map(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Map> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Map> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pacman.protobuf.Map getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

