// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public interface MapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.Map)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sizeX = 1;</code>
   * @return The sizeX.
   */
  int getSizeX();

  /**
   * <code>int32 sizeY = 2;</code>
   * @return The sizeY.
   */
  int getSizeY();

  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  java.util.List<com.pacman.protobuf.Map.Cell> 
      getCellsList();
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  com.pacman.protobuf.Map.Cell getCells(int index);
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  int getCellsCount();
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  java.util.List<? extends com.pacman.protobuf.Map.CellOrBuilder> 
      getCellsOrBuilderList();
  /**
   * <code>repeated .com.pacman.protobuf.Map.Cell cells = 4;</code>
   */
  com.pacman.protobuf.Map.CellOrBuilder getCellsOrBuilder(
      int index);
}
