// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.pacman.protobuf.Map map = 1;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <code>.com.pacman.protobuf.Map map = 1;</code>
   * @return The map.
   */
  com.pacman.protobuf.Map getMap();
  /**
   * <code>.com.pacman.protobuf.Map map = 1;</code>
   */
  com.pacman.protobuf.MapOrBuilder getMapOrBuilder();

  /**
   * <code>.com.pacman.protobuf.Players players = 2;</code>
   * @return Whether the players field is set.
   */
  boolean hasPlayers();
  /**
   * <code>.com.pacman.protobuf.Players players = 2;</code>
   * @return The players.
   */
  com.pacman.protobuf.Players getPlayers();
  /**
   * <code>.com.pacman.protobuf.Players players = 2;</code>
   */
  com.pacman.protobuf.PlayersOrBuilder getPlayersOrBuilder();
}
