// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_Map_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_Map_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_Map_Cell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_Map_Cell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_Players_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_Players_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pacman_protobuf_MoveCommands_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pacman_protobuf_MoveCommands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!com/pacman/protobuf/message.proto\022\023com" +
      ".pacman.protobuf\"\317\001\n\003Map\022\r\n\005sizeX\030\001 \001(\005\022" +
      "\r\n\005sizeY\030\002 \001(\005\022,\n\005cells\030\004 \003(\0132\035.com.pacm" +
      "an.protobuf.Map.Cell\032O\n\004Cell\022\t\n\001x\030\001 \001(\005\022" +
      "\t\n\001y\030\002 \001(\005\0221\n\005state\030\003 \001(\0162\".com.pacman.p" +
      "rotobuf.Map.CellState\"+\n\tCellState\022\010\n\004WA" +
      "LL\020\000\022\t\n\005EMPTY\020\001\022\t\n\005POINT\020\002\"{\n\006Player\022\014\n\004" +
      "posX\030\001 \001(\005\022\014\n\004posY\030\002 \001(\005\022\n\n\002ID\030\003 \001(\t\0225\n\t" +
      "direction\030\004 \001(\0162\".com.pacman.protobuf.Mo" +
      "veDirection\022\022\n\nmoveTimeMS\030\005 \001(\005\"7\n\007Playe" +
      "rs\022,\n\007players\030\001 \003(\0132\033.com.pacman.protobu" +
      "f.Player\"_\n\007Message\022%\n\003map\030\001 \001(\0132\030.com.p" +
      "acman.protobuf.Map\022-\n\007players\030\002 \001(\0132\034.co" +
      "m.pacman.protobuf.Players\"R\n\014MoveCommand" +
      "s\0226\n\ndirections\030\001 \003(\0162\".com.pacman.proto" +
      "buf.MoveDirection\022\n\n\002ID\030\002 \001(\t*?\n\rMoveDir" +
      "ection\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\022\t\n\005RIGHT\020\002\022\010\n\004L" +
      "EFT\020\003\022\007\n\003NON\020\004B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_pacman_protobuf_Map_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pacman_protobuf_Map_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_Map_descriptor,
        new java.lang.String[] { "SizeX", "SizeY", "Cells", });
    internal_static_com_pacman_protobuf_Map_Cell_descriptor =
      internal_static_com_pacman_protobuf_Map_descriptor.getNestedTypes().get(0);
    internal_static_com_pacman_protobuf_Map_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_Map_Cell_descriptor,
        new java.lang.String[] { "X", "Y", "State", });
    internal_static_com_pacman_protobuf_Player_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pacman_protobuf_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_Player_descriptor,
        new java.lang.String[] { "PosX", "PosY", "ID", "Direction", "MoveTimeMS", });
    internal_static_com_pacman_protobuf_Players_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_pacman_protobuf_Players_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_Players_descriptor,
        new java.lang.String[] { "Players", });
    internal_static_com_pacman_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_pacman_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_Message_descriptor,
        new java.lang.String[] { "Map", "Players", });
    internal_static_com_pacman_protobuf_MoveCommands_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_pacman_protobuf_MoveCommands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pacman_protobuf_MoveCommands_descriptor,
        new java.lang.String[] { "Directions", "ID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
