// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

/**
 * Protobuf enum {@code com.pacman.protobuf.MoveDirection}
 */
public enum MoveDirection
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UP = 0;</code>
   */
  UP(0),
  /**
   * <code>DOWN = 1;</code>
   */
  DOWN(1),
  /**
   * <code>RIGHT = 2;</code>
   */
  RIGHT(2),
  /**
   * <code>LEFT = 3;</code>
   */
  LEFT(3),
  /**
   * <code>NON = 4;</code>
   */
  NON(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UP = 0;</code>
   */
  public static final int UP_VALUE = 0;
  /**
   * <code>DOWN = 1;</code>
   */
  public static final int DOWN_VALUE = 1;
  /**
   * <code>RIGHT = 2;</code>
   */
  public static final int RIGHT_VALUE = 2;
  /**
   * <code>LEFT = 3;</code>
   */
  public static final int LEFT_VALUE = 3;
  /**
   * <code>NON = 4;</code>
   */
  public static final int NON_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MoveDirection valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MoveDirection forNumber(int value) {
    switch (value) {
      case 0: return UP;
      case 1: return DOWN;
      case 2: return RIGHT;
      case 3: return LEFT;
      case 4: return NON;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MoveDirection>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MoveDirection> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MoveDirection>() {
          public MoveDirection findValueByNumber(int number) {
            return MoveDirection.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pacman.protobuf.MessageOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MoveDirection[] VALUES = values();

  public static MoveDirection valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MoveDirection(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.pacman.protobuf.MoveDirection)
}

