// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public interface MoveCommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.MoveCommands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return A list containing the directions.
   */
  java.util.List<com.pacman.protobuf.MoveDirection> getDirectionsList();
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return The count of directions.
   */
  int getDirectionsCount();
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @param index The index of the element to return.
   * @return The directions at the given index.
   */
  com.pacman.protobuf.MoveDirection getDirections(int index);
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return A list containing the enum numeric values on the wire for directions.
   */
  java.util.List<java.lang.Integer>
  getDirectionsValueList();
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of directions at the given index.
   */
  int getDirectionsValue(int index);

  /**
   * <code>string ID = 2;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string ID = 2;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
