// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

/**
 * Protobuf type {@code com.pacman.protobuf.MoveCommands}
 */
public final class MoveCommands extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.pacman.protobuf.MoveCommands)
    MoveCommandsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MoveCommands.newBuilder() to construct.
  private MoveCommands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MoveCommands() {
    directions_ = java.util.Collections.emptyList();
    iD_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MoveCommands();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MoveCommands(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              directions_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            directions_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                directions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              directions_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            iD_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        directions_ = java.util.Collections.unmodifiableList(directions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_MoveCommands_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_MoveCommands_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pacman.protobuf.MoveCommands.class, com.pacman.protobuf.MoveCommands.Builder.class);
  }

  public static final int DIRECTIONS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> directions_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.pacman.protobuf.MoveDirection> directions_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.pacman.protobuf.MoveDirection>() {
            public com.pacman.protobuf.MoveDirection convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              com.pacman.protobuf.MoveDirection result = com.pacman.protobuf.MoveDirection.valueOf(from);
              return result == null ? com.pacman.protobuf.MoveDirection.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return A list containing the directions.
   */
  @java.lang.Override
  public java.util.List<com.pacman.protobuf.MoveDirection> getDirectionsList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.pacman.protobuf.MoveDirection>(directions_, directions_converter_);
  }
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return The count of directions.
   */
  @java.lang.Override
  public int getDirectionsCount() {
    return directions_.size();
  }
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @param index The index of the element to return.
   * @return The directions at the given index.
   */
  @java.lang.Override
  public com.pacman.protobuf.MoveDirection getDirections(int index) {
    return directions_converter_.convert(directions_.get(index));
  }
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @return A list containing the enum numeric values on the wire for directions.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getDirectionsValueList() {
    return directions_;
  }
  /**
   * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of directions at the given index.
   */
  @java.lang.Override
  public int getDirectionsValue(int index) {
    return directions_.get(index);
  }
  private int directionsMemoizedSerializedSize;

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object iD_;
  /**
   * <code>string ID = 2;</code>
   * @return The iD.
   */
  @java.lang.Override
  public java.lang.String getID() {
    java.lang.Object ref = iD_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iD_ = s;
      return s;
    }
  }
  /**
   * <code>string ID = 2;</code>
   * @return The bytes for iD.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIDBytes() {
    java.lang.Object ref = iD_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iD_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getDirectionsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(directionsMemoizedSerializedSize);
    }
    for (int i = 0; i < directions_.size(); i++) {
      output.writeEnumNoTag(directions_.get(i));
    }
    if (!getIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iD_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < directions_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(directions_.get(i));
      }
      size += dataSize;
      if (!getDirectionsList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }directionsMemoizedSerializedSize = dataSize;
    }
    if (!getIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iD_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pacman.protobuf.MoveCommands)) {
      return super.equals(obj);
    }
    com.pacman.protobuf.MoveCommands other = (com.pacman.protobuf.MoveCommands) obj;

    if (!directions_.equals(other.directions_)) return false;
    if (!getID()
        .equals(other.getID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDirectionsCount() > 0) {
      hash = (37 * hash) + DIRECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + directions_.hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pacman.protobuf.MoveCommands parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.MoveCommands parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.MoveCommands parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.MoveCommands parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pacman.protobuf.MoveCommands prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.pacman.protobuf.MoveCommands}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.pacman.protobuf.MoveCommands)
      com.pacman.protobuf.MoveCommandsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_MoveCommands_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_MoveCommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pacman.protobuf.MoveCommands.class, com.pacman.protobuf.MoveCommands.Builder.class);
    }

    // Construct using com.pacman.protobuf.MoveCommands.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      directions_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      iD_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_MoveCommands_descriptor;
    }

    @java.lang.Override
    public com.pacman.protobuf.MoveCommands getDefaultInstanceForType() {
      return com.pacman.protobuf.MoveCommands.getDefaultInstance();
    }

    @java.lang.Override
    public com.pacman.protobuf.MoveCommands build() {
      com.pacman.protobuf.MoveCommands result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pacman.protobuf.MoveCommands buildPartial() {
      com.pacman.protobuf.MoveCommands result = new com.pacman.protobuf.MoveCommands(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        directions_ = java.util.Collections.unmodifiableList(directions_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.directions_ = directions_;
      result.iD_ = iD_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pacman.protobuf.MoveCommands) {
        return mergeFrom((com.pacman.protobuf.MoveCommands)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pacman.protobuf.MoveCommands other) {
      if (other == com.pacman.protobuf.MoveCommands.getDefaultInstance()) return this;
      if (!other.directions_.isEmpty()) {
        if (directions_.isEmpty()) {
          directions_ = other.directions_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDirectionsIsMutable();
          directions_.addAll(other.directions_);
        }
        onChanged();
      }
      if (!other.getID().isEmpty()) {
        iD_ = other.iD_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pacman.protobuf.MoveCommands parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pacman.protobuf.MoveCommands) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> directions_ =
      java.util.Collections.emptyList();
    private void ensureDirectionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        directions_ = new java.util.ArrayList<java.lang.Integer>(directions_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @return A list containing the directions.
     */
    public java.util.List<com.pacman.protobuf.MoveDirection> getDirectionsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.pacman.protobuf.MoveDirection>(directions_, directions_converter_);
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @return The count of directions.
     */
    public int getDirectionsCount() {
      return directions_.size();
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param index The index of the element to return.
     * @return The directions at the given index.
     */
    public com.pacman.protobuf.MoveDirection getDirections(int index) {
      return directions_converter_.convert(directions_.get(index));
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param index The index to set the value at.
     * @param value The directions to set.
     * @return This builder for chaining.
     */
    public Builder setDirections(
        int index, com.pacman.protobuf.MoveDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDirectionsIsMutable();
      directions_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param value The directions to add.
     * @return This builder for chaining.
     */
    public Builder addDirections(com.pacman.protobuf.MoveDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDirectionsIsMutable();
      directions_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param values The directions to add.
     * @return This builder for chaining.
     */
    public Builder addAllDirections(
        java.lang.Iterable<? extends com.pacman.protobuf.MoveDirection> values) {
      ensureDirectionsIsMutable();
      for (com.pacman.protobuf.MoveDirection value : values) {
        directions_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirections() {
      directions_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @return A list containing the enum numeric values on the wire for directions.
     */
    public java.util.List<java.lang.Integer>
    getDirectionsValueList() {
      return java.util.Collections.unmodifiableList(directions_);
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of directions at the given index.
     */
    public int getDirectionsValue(int index) {
      return directions_.get(index);
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of directions at the given index.
     * @return This builder for chaining.
     */
    public Builder setDirectionsValue(
        int index, int value) {
      ensureDirectionsIsMutable();
      directions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param value The enum numeric value on the wire for directions to add.
     * @return This builder for chaining.
     */
    public Builder addDirectionsValue(int value) {
      ensureDirectionsIsMutable();
      directions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.pacman.protobuf.MoveDirection directions = 1;</code>
     * @param values The enum numeric values on the wire for directions to add.
     * @return This builder for chaining.
     */
    public Builder addAllDirectionsValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureDirectionsIsMutable();
      for (int value : values) {
        directions_.add(value);
      }
      onChanged();
      return this;
    }

    private java.lang.Object iD_ = "";
    /**
     * <code>string ID = 2;</code>
     * @return The iD.
     */
    public java.lang.String getID() {
      java.lang.Object ref = iD_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iD_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ID = 2;</code>
     * @return The bytes for iD.
     */
    public com.google.protobuf.ByteString
        getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ID = 2;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      
      iD_ = getDefaultInstance().getID();
      onChanged();
      return this;
    }
    /**
     * <code>string ID = 2;</code>
     * @param value The bytes for iD to set.
     * @return This builder for chaining.
     */
    public Builder setIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iD_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.pacman.protobuf.MoveCommands)
  }

  // @@protoc_insertion_point(class_scope:com.pacman.protobuf.MoveCommands)
  private static final com.pacman.protobuf.MoveCommands DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pacman.protobuf.MoveCommands();
  }

  public static com.pacman.protobuf.MoveCommands getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveCommands>
      PARSER = new com.google.protobuf.AbstractParser<MoveCommands>() {
    @java.lang.Override
    public MoveCommands parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MoveCommands(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MoveCommands> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveCommands> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pacman.protobuf.MoveCommands getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

