// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

/**
 * Protobuf type {@code com.pacman.protobuf.Player}
 */
public final class Player extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.pacman.protobuf.Player)
    PlayerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Player.newBuilder() to construct.
  private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Player() {
    iD_ = "";
    direction_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Player();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Player(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            posX_ = input.readInt32();
            break;
          }
          case 16: {

            posY_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            iD_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          case 40: {

            moveTimeMS_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Player_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Player_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pacman.protobuf.Player.class, com.pacman.protobuf.Player.Builder.class);
  }

  public static final int POSX_FIELD_NUMBER = 1;
  private int posX_;
  /**
   * <code>int32 posX = 1;</code>
   * @return The posX.
   */
  @java.lang.Override
  public int getPosX() {
    return posX_;
  }

  public static final int POSY_FIELD_NUMBER = 2;
  private int posY_;
  /**
   * <code>int32 posY = 2;</code>
   * @return The posY.
   */
  @java.lang.Override
  public int getPosY() {
    return posY_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object iD_;
  /**
   * <code>string ID = 3;</code>
   * @return The iD.
   */
  @java.lang.Override
  public java.lang.String getID() {
    java.lang.Object ref = iD_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iD_ = s;
      return s;
    }
  }
  /**
   * <code>string ID = 3;</code>
   * @return The bytes for iD.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIDBytes() {
    java.lang.Object ref = iD_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iD_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 4;
  private int direction_;
  /**
   * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
   * @return The direction.
   */
  @java.lang.Override public com.pacman.protobuf.MoveDirection getDirection() {
    @SuppressWarnings("deprecation")
    com.pacman.protobuf.MoveDirection result = com.pacman.protobuf.MoveDirection.valueOf(direction_);
    return result == null ? com.pacman.protobuf.MoveDirection.UNRECOGNIZED : result;
  }

  public static final int MOVETIMEMS_FIELD_NUMBER = 5;
  private int moveTimeMS_;
  /**
   * <code>int32 moveTimeMS = 5;</code>
   * @return The moveTimeMS.
   */
  @java.lang.Override
  public int getMoveTimeMS() {
    return moveTimeMS_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (posX_ != 0) {
      output.writeInt32(1, posX_);
    }
    if (posY_ != 0) {
      output.writeInt32(2, posY_);
    }
    if (!getIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iD_);
    }
    if (direction_ != com.pacman.protobuf.MoveDirection.UP.getNumber()) {
      output.writeEnum(4, direction_);
    }
    if (moveTimeMS_ != 0) {
      output.writeInt32(5, moveTimeMS_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (posX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, posX_);
    }
    if (posY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, posY_);
    }
    if (!getIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iD_);
    }
    if (direction_ != com.pacman.protobuf.MoveDirection.UP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, direction_);
    }
    if (moveTimeMS_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, moveTimeMS_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pacman.protobuf.Player)) {
      return super.equals(obj);
    }
    com.pacman.protobuf.Player other = (com.pacman.protobuf.Player) obj;

    if (getPosX()
        != other.getPosX()) return false;
    if (getPosY()
        != other.getPosY()) return false;
    if (!getID()
        .equals(other.getID())) return false;
    if (direction_ != other.direction_) return false;
    if (getMoveTimeMS()
        != other.getMoveTimeMS()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSX_FIELD_NUMBER;
    hash = (53 * hash) + getPosX();
    hash = (37 * hash) + POSY_FIELD_NUMBER;
    hash = (53 * hash) + getPosY();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (37 * hash) + MOVETIMEMS_FIELD_NUMBER;
    hash = (53 * hash) + getMoveTimeMS();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pacman.protobuf.Player parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Player parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Player parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Player parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Player parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pacman.protobuf.Player parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pacman.protobuf.Player parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Player parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.Player parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Player parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pacman.protobuf.Player parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pacman.protobuf.Player parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pacman.protobuf.Player prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.pacman.protobuf.Player}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.pacman.protobuf.Player)
      com.pacman.protobuf.PlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pacman.protobuf.Player.class, com.pacman.protobuf.Player.Builder.class);
    }

    // Construct using com.pacman.protobuf.Player.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      posX_ = 0;

      posY_ = 0;

      iD_ = "";

      direction_ = 0;

      moveTimeMS_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pacman.protobuf.MessageOuterClass.internal_static_com_pacman_protobuf_Player_descriptor;
    }

    @java.lang.Override
    public com.pacman.protobuf.Player getDefaultInstanceForType() {
      return com.pacman.protobuf.Player.getDefaultInstance();
    }

    @java.lang.Override
    public com.pacman.protobuf.Player build() {
      com.pacman.protobuf.Player result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pacman.protobuf.Player buildPartial() {
      com.pacman.protobuf.Player result = new com.pacman.protobuf.Player(this);
      result.posX_ = posX_;
      result.posY_ = posY_;
      result.iD_ = iD_;
      result.direction_ = direction_;
      result.moveTimeMS_ = moveTimeMS_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pacman.protobuf.Player) {
        return mergeFrom((com.pacman.protobuf.Player)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pacman.protobuf.Player other) {
      if (other == com.pacman.protobuf.Player.getDefaultInstance()) return this;
      if (other.getPosX() != 0) {
        setPosX(other.getPosX());
      }
      if (other.getPosY() != 0) {
        setPosY(other.getPosY());
      }
      if (!other.getID().isEmpty()) {
        iD_ = other.iD_;
        onChanged();
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      if (other.getMoveTimeMS() != 0) {
        setMoveTimeMS(other.getMoveTimeMS());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pacman.protobuf.Player parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pacman.protobuf.Player) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int posX_ ;
    /**
     * <code>int32 posX = 1;</code>
     * @return The posX.
     */
    @java.lang.Override
    public int getPosX() {
      return posX_;
    }
    /**
     * <code>int32 posX = 1;</code>
     * @param value The posX to set.
     * @return This builder for chaining.
     */
    public Builder setPosX(int value) {
      
      posX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 posX = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosX() {
      
      posX_ = 0;
      onChanged();
      return this;
    }

    private int posY_ ;
    /**
     * <code>int32 posY = 2;</code>
     * @return The posY.
     */
    @java.lang.Override
    public int getPosY() {
      return posY_;
    }
    /**
     * <code>int32 posY = 2;</code>
     * @param value The posY to set.
     * @return This builder for chaining.
     */
    public Builder setPosY(int value) {
      
      posY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 posY = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosY() {
      
      posY_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object iD_ = "";
    /**
     * <code>string ID = 3;</code>
     * @return The iD.
     */
    public java.lang.String getID() {
      java.lang.Object ref = iD_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iD_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ID = 3;</code>
     * @return The bytes for iD.
     */
    public com.google.protobuf.ByteString
        getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ID = 3;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      
      iD_ = getDefaultInstance().getID();
      onChanged();
      return this;
    }
    /**
     * <code>string ID = 3;</code>
     * @param value The bytes for iD to set.
     * @return This builder for chaining.
     */
    public Builder setIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iD_ = value;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
     * @return The direction.
     */
    @java.lang.Override
    public com.pacman.protobuf.MoveDirection getDirection() {
      @SuppressWarnings("deprecation")
      com.pacman.protobuf.MoveDirection result = com.pacman.protobuf.MoveDirection.valueOf(direction_);
      return result == null ? com.pacman.protobuf.MoveDirection.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(com.pacman.protobuf.MoveDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int moveTimeMS_ ;
    /**
     * <code>int32 moveTimeMS = 5;</code>
     * @return The moveTimeMS.
     */
    @java.lang.Override
    public int getMoveTimeMS() {
      return moveTimeMS_;
    }
    /**
     * <code>int32 moveTimeMS = 5;</code>
     * @param value The moveTimeMS to set.
     * @return This builder for chaining.
     */
    public Builder setMoveTimeMS(int value) {
      
      moveTimeMS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 moveTimeMS = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoveTimeMS() {
      
      moveTimeMS_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.pacman.protobuf.Player)
  }

  // @@protoc_insertion_point(class_scope:com.pacman.protobuf.Player)
  private static final com.pacman.protobuf.Player DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pacman.protobuf.Player();
  }

  public static com.pacman.protobuf.Player getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Player>
      PARSER = new com.google.protobuf.AbstractParser<Player>() {
    @java.lang.Override
    public Player parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Player(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Player> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Player> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pacman.protobuf.Player getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

