// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public interface PlayersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.Players)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.pacman.protobuf.Player players = 1;</code>
   */
  java.util.List<com.pacman.protobuf.Player> 
      getPlayersList();
  /**
   * <code>repeated .com.pacman.protobuf.Player players = 1;</code>
   */
  com.pacman.protobuf.Player getPlayers(int index);
  /**
   * <code>repeated .com.pacman.protobuf.Player players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .com.pacman.protobuf.Player players = 1;</code>
   */
  java.util.List<? extends com.pacman.protobuf.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .com.pacman.protobuf.Player players = 1;</code>
   */
  com.pacman.protobuf.PlayerOrBuilder getPlayersOrBuilder(
      int index);
}
