// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pacman/protobuf/message.proto

package com.pacman.protobuf;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pacman.protobuf.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 posX = 1;</code>
   * @return The posX.
   */
  int getPosX();

  /**
   * <code>int32 posY = 2;</code>
   * @return The posY.
   */
  int getPosY();

  /**
   * <code>string ID = 3;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string ID = 3;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();

  /**
   * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.com.pacman.protobuf.MoveDirection direction = 4;</code>
   * @return The direction.
   */
  com.pacman.protobuf.MoveDirection getDirection();

  /**
   * <code>int32 moveTimeMS = 5;</code>
   * @return The moveTimeMS.
   */
  int getMoveTimeMS();
}
